#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

/// @brief Cryptographic services used by the application layer.
///
/// The class deliberately operates on byte buffers only. It does not know
/// about Vault, files, or the serializer; those responsibilities belong to
/// higher layers.
class Crypto {
public:
    /// @brief Byte container exchanged with cryptographic operations.
    using Bytes = std::vector<std::uint8_t>;

    /// @brief Parameters used by Argon2id key derivation.
    struct KdfParameters {
        /// @brief Maximum number of Argon2id passes.
        std::uint64_t ops_limit;

        /// @brief Maximum amount of memory used by Argon2id, in bytes.
        std::size_t memory_limit;
    };

    /// @brief Authenticated ciphertext and the nonce required to decrypt it.
    struct EncryptedPayload {
        /// @brief Public XChaCha20-Poly1305 nonce.
        Bytes nonce;

        /// @brief Ciphertext including the Poly1305 authentication tag.
        Bytes ciphertext;
    };

    /// @brief Number of bytes required by XChaCha20-Poly1305 keys.
    static constexpr std::size_t kKeyBytes = 32;

    /// @brief Number of bytes required by the Argon2id salt.
    static constexpr std::size_t kSaltBytes = 16;

    /// @brief Number of bytes required by an XChaCha20-Poly1305 nonce.
    static constexpr std::size_t kNonceBytes = 24;

    /// @brief Number of bytes added by the XChaCha20-Poly1305 authentication tag.
    static constexpr std::size_t kAuthenticationTagBytes = 16;

    /// @brief Construct an uninitialized cryptographic service.
    Crypto() = default;

    /// @brief Initialize libsodium before cryptographic operations are used.
    /// @param error Output description when initialization fails.
    /// @return True when libsodium is ready, false otherwise.
    bool initialize(std::string& error);

    /// @brief Report whether libsodium has been initialized successfully.
    /// @return True when cryptographic operations can be requested.
    bool is_initialized() const noexcept;

    /// @brief Return the recommended Argon2id parameters for a desktop vault.
    /// @return Libsodium's MODERATE CPU and memory limits.
    static KdfParameters recommended_kdf_parameters() noexcept;

    /// @brief Generate cryptographically secure random bytes.
    /// @param size Number of bytes to generate.
    /// @param output Destination buffer replaced with the generated bytes.
    /// @param error Output description when generation fails.
    /// @return True when random bytes were generated, false otherwise.
    bool random_bytes(std::size_t size, Bytes& output, std::string& error) const;

    /// @brief Derive the fixed-size encryption key from a password and salt.
    /// @param password Password used as the key derivation input.
    /// @param salt Unique public salt associated with the encrypted payload.
    /// @param parameters Argon2id CPU and memory limits.
    /// @param key Destination buffer replaced with a 32-byte key.
    /// @param error Output description when derivation fails.
    /// @return True when Argon2id derives a key, false otherwise.
    bool derive_key(std::string_view password,
                    const Bytes& salt,
                    const KdfParameters& parameters,
                    Bytes& key,
                    std::string& error) const;

    /// @brief Encrypt and authenticate one complete payload.
    /// @param plaintext Data to encrypt.
    /// @param key 32-byte XChaCha20-Poly1305 key.
    /// @param associated_data Metadata authenticated but not encrypted.
    /// @param output Destination payload replaced with a nonce and ciphertext.
    /// @param error Output description when encryption fails.
    /// @return True when encryption succeeds, false otherwise.
    bool encrypt(const Bytes& plaintext,
                 const Bytes& key,
                 const Bytes& associated_data,
                 EncryptedPayload& output,
                 std::string& error) const;

    /// @brief Decrypt and authenticate one complete payload.
    /// @param input Payload containing the nonce and authenticated ciphertext.
    /// @param key 32-byte XChaCha20-Poly1305 key.
    /// @param associated_data Metadata that was authenticated during encryption.
    /// @param plaintext Destination buffer replaced with decrypted data.
    /// @param error General error for an invalid key or altered payload.
    /// @return True when authentication and decryption succeed.
    bool decrypt(const EncryptedPayload& input,
                 const Bytes& key,
                 const Bytes& associated_data,
                 Bytes& plaintext,
                 std::string& error) const;

    /// @brief Wipe sensitive bytes with libsodium's secure memory primitive.
    /// @param bytes Buffer containing sensitive material.
    static void clear(Bytes& bytes) noexcept;

    /// @brief Wipe sensitive text with libsodium's secure memory primitive.
    /// @param text String containing sensitive material.
    static void clear(std::string& text) noexcept;

private:
    /// @brief Whether libsodium has been initialized for this service.
    bool initialized_ = false;
};
